### PR TITLE
added refs for plotting with ggplot

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Some useful links for ggplot cheat sheets and examples.

### CODE REVIEW

**Comment by cbahlai** [comment]
Thanks Bastian!

**Comment by gedankenstuecke** [comment]
Happy to help out! Anything that needs urgent help?

**Comment by cbahlai** [comment]
I just finished getting the lesson for today together, so phew! I'll be populating more lessons tomorrow so I can get my experts lined up- any content you want to suggest beyond lecture 8 or so?

**Comment by gedankenstuecke** [comment]
Sure, I'll have a look :)

**Pull request merged**
